#!/bin/sh

start_server()
{
	pid=`/bin/pidof webResSrv`
	if [ -n "$pid" ]; then
		return;
	fi		

	export LD_LIBRARY_PATH=/home/sky/ehomeserver/lib/:$LD_LIBRARY_PATH
	/opt/webResServer/webResSrv&
}

stop_server()
{
	pid=`/bin/pidof webResSrv`
	if [ -n "$pid" ]; then
		kill -9 $pid
	fi
}

case "$1" in
  start)
	start_server
	;;

  stop)
	stop_server
	;;

  restart)
	stop_server
	start_server
	;;

esac

exit 0